[project]
name = "applied-statistics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipykernel>=6.29.5",
    "matplotlib>=3.9.2",
    "notebook>=7.2.2",
    "scikit-learn>=1.5.2",
    "ucimlrepo>=0.0.7",
]
